version: '3.8'

services:
  # CRM Frontend Application - Production
  crm-frontend:
    image: syedus06/crm-frontend:${CRM_VERSION:-latest}
    container_name: crm-frontend-prod
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      timeout: 30s
      interval: 30s
      retries: 3
    networks:
      - crm-production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Nginx reverse proxy for SSL termination
  # nginx:
  #   image: nginx:alpine
  #   container_name: crm-nginx
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - crm-frontend
  #   networks:
  #     - crm-production

networks:
  crm-production:
    driver: bridge