version: '3.8'

services:
  crm-frontend:
    image: syedus06/crm-frontend:latest
    container_name: crm-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - AUTH_SECRET=LfC5p+WilVcw35ctYr/8pdptnUgTw4+5tKStaVrWYLU=
      - AUTH_URL=https://dev.crmcup.com
      - AUTH_KEYCLOAK_ID=crm-frontend
      - AUTH_KEYCLOAK_SECRET=YOUR_KEYCLOAK_CLIENT_SECRET_HERE
      - AUTH_KEYCLOAK_ISSUER=https://auth.dev.crmcup.com/realms/crm
      - NEXTAUTH_URL=https://dev.crmcup.com
      - NODE_ENV=production
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
