version: '3.8'

services:
  # CRM Frontend Application
  crm-frontend:
    image: syedus06/crm-frontend:latest
    container_name: crm-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      timeout: 30s
      interval: 30s
      retries: 3
    networks:
      - crm-network

  # Optional: Add database service if needed
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: crm-postgres
  #   environment:
  #     POSTGRES_DB: crm
  #     POSTGRES_USER: crm_user
  #     POSTGRES_PASSWORD: crm_password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - crm-network

  # Optional: Add Keycloak service for authentication
  # keycloak:
  #   image: quay.io/keycloak/keycloak:23.0
  #   container_name: crm-keycloak
  #   environment:
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: admin
  #     KC_DB: postgres
  #     KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
  #     KC_DB_USERNAME: keycloak_user
  #     KC_DB_PASSWORD: keycloak_password
  #   ports:
  #     - "9080:8080"
  #   depends_on:
  #     - postgres
  #   command: start-dev
  #   networks:
  #     - crm-network

networks:
  crm-network:
    driver: bridge

# volumes:
#   postgres_data: