name: Build and Publish to Docker Hub

on:
  push:
    branches: [main, master, develop]
    tags: ["v*"]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to build for"
        required: true
        default: "production"
        type: choice
        options:
          - development
          - production

env:
  # Docker Hub Configuration - CHANGE YOUR USERNAME
  IMAGE_NAME: syedus06/crm-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine environment file
        id: env-config
        run: |
          if [ "${{ github.event.inputs.environment }}" = "development" ] || [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "env_file=.env" >> $GITHUB_OUTPUT
            echo "env_suffix=-dev" >> $GITHUB_OUTPUT
            echo "node_env=development" >> $GITHUB_OUTPUT
          else
            echo "env_file=.env.production" >> $GITHUB_OUTPUT
            echo "env_suffix=" >> $GITHUB_OUTPUT
            echo "node_env=production" >> $GITHUB_OUTPUT
          fi

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,suffix=${{ steps.env-config.outputs.env_suffix }}
            type=ref,event=pr,suffix=${{ steps.env-config.outputs.env_suffix }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}},suffix=${{ steps.env-config.outputs.env_suffix }}

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=${{ steps.env-config.outputs.node_env }}
            NEXT_TELEMETRY_DISABLED=1
            ENV_FILE=${{ steps.env-config.outputs.env_file }}
