name: 🐳 Frontend CI/CD

permissions:
  contents: read

on:
  push:
    branches: [master]
  workflow_call:
    inputs:
      image_tag:
        description: 'Docker image tag'
        required: false
        type: string
        default: 'latest'

jobs:
  build_frontend:
    name: Build Frontend Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine image tag
        id: tag
        run: |
          if [ "${{ inputs.image_tag }}" != "" ]; then
            echo "IMAGE_TAG=${{ inputs.image_tag }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/crm-frontend:${{ env.IMAGE_TAG }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Display build info
        run: |
          echo "✅ Frontend image built and pushed:"
          echo "🐳 ${{ secrets.DOCKER_USERNAME }}/crm-frontend:${{ env.IMAGE_TAG }}"
